name: Development
on:
  push:
    branches: [ "Dev" ]
  workflow_dispatch:
jobs:
  build_and_push_to_docker_hub:
      name: Push Docker image to Docker Hub
      runs-on: ubuntu-latest

      steps:
      -
        name: Check out the repo
        uses: actions/checkout@v2
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      -
        name: Login to Docker
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      -
        name: Push Fastapi application to Docker Hub
        uses: docker/build-push-action@v2
        with:
          context: app
          push: true
          tags: alfa/plans-fastapi:latest

  deploy:
      name: Deploy to the remote server
      runs-on: ubuntu-latest
      needs: build_and_push_to_docker_hub

      steps:
      -
        name: Executing remote ssh commands to deploy
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USER }}
          key: ${{ secrets.SSH_KEY }}
          passphrase: ${{ secrets.SSH_PASSPHRASE }}
          script: |
            sudo docker pull alfa/plans-fastapi:latest
            cd ~/infra
            sudo docker compose --env-file=env/.general down
            sudo docker compose --env-file=env/.general up -d
            sudo docker image prune -f
